[versions]
agp = "8.13.1"
#noinspection UnusedVersionCatalogEntry
android-compileSdk = "36"
#noinspection UnusedVersionCatalogEntry
android-minSdk = "24"
#noinspection UnusedVersionCatalogEntry
android-targetSdk = "36"
androidx-activityCompose = "1.12.0"
androidx-splash = "1.2.0"
buildKonfig = "0.17.1"
compose-plugin = "1.9.3"
detektFormatting = "1.23.8"
filekitCompose = "0.8.8"
firebaseMessaging = "25.0.1"
kotlin = "2.3.0-RC"
ktor = "3.3.2"
coroutines = "1.10.2"
decompose = "3.4.0"
essenty = "2.5.0"
kotlinxSerializationJson = "1.9.0"
multiplatformSettings = "1.3.0"
ninemensmorris = "1.0.4"
uiTestJunit4Android = "1.9.5"
roborazzi = "1.51.0"
storytale = "0.0.4-alpha01+dev18"
macroBenchmark = "1.4.1"
junit = "1.3.0"
espressoCore = "3.7.0"
uiautomator = "2.3.0"
baselineprofile = "1.4.1"
screenshot = "0.0.1-alpha11"
koinCore = "4.1.1"
detekt = "2.0.0-alpha.1"
gms = "4.4.4"
workRuntimeKtx = "2.11.0"
workManager = "2.11.0"
room = "2.7.2"
ksp = "2.3.3"
datastore = "1.1.1"

[libraries]
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-splash" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activityCompose" }
androidx-ui-test = { module = "androidx.compose.ui:ui-test", version.ref = "uiTestJunit4Android" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "uiTestJunit4Android" }

androidx-workmanager = { module = "androidx.work:work-runtime-ktx", version.ref = "workManager" }
buildkonfig-gradle-plugin = { module = "com.codingfeline.buildkonfig:buildkonfig-gradle-plugin", version.ref = "buildKonfig" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detektFormatting" }
filekit-compose = { module = "io.github.vinceglb:filekit-compose", version.ref = "filekitCompose" }

firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-client-js = { group = "io.ktor", name = "ktor-client-js", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-serialization-kotlinx-protobuf = { group = "io.ktor", name = "ktor-serialization-kotlinx-protobuf", version.ref = "ktor" }

decompose = { group = "com.arkivanov.decompose", name = "decompose", version.ref = "decompose" }
decompose-lifecycle = { group = "com.arkivanov.essenty", name = "lifecycle", version.ref = "essenty" }
decompose-state-keeper = { group = "com.arkivanov.essenty", name = "state-keeper", version.ref = "essenty" }
decompose-animations = { group = "com.arkivanov.decompose", name = "extensions-compose-experimental", version.ref = "decompose" }

kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinx-serialization-protobuf = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-protobuf", version.ref = "kotlinxSerializationJson" }

multiplatform-settings = { group = "com.russhwolf", name = "multiplatform-settings", version.ref = "multiplatformSettings" }
multiplatform-settings-no-arg = { group = "com.russhwolf", name = "multiplatform-settings-no-arg", version.ref = "multiplatformSettings" }

multiplatform-settings-test = { module = "com.russhwolf:multiplatform-settings-test", version.ref = "multiplatformSettings" }
ninemensmorris = { group = "io.github.kroune", name = "nineMensMorris", version.ref = "ninemensmorris" }

macro-benchmark = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "macroBenchmark"}
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling"}
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koinCore" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinCore" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi"}
storytale = { id = "org.jetbrains.compose.storytale", version.ref = "storytale" }
android-test = { id = "com.android.test", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
baseline-profile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }
build-konfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildKonfig" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
detekt = { id = "dev.detekt", version.ref = "detekt" }
screenshot = { id = "com.android.compose.screenshot", version.ref = "screenshot"}
gms = { id = "com.google.gms.google-services", version.ref = "gms"}

google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }